# -*- coding: utf-8 -*-
"""19.01.26training session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXMBSRpTUQgoBbv6b6BLWBXugwAIEnJs
"""

if (12 and 24):
  print("Hello")
else:
  print("Hi")

a= int(input("Enter  a value for A:"))
b=int(input("Enter a value for B:"))
c= a+b
print("Addition of two number is :", c)

if (c==a):
  print("right")
else:
  print("wrong")

a= int(input("Enter  a value for A:"))
b=int(input("Enter a value for B:"))
c= a+b
print("Addition of two number is :", c)

if (c==a):
  print("right")
else:
  print("wrong")

